### ISSUE TITLE
🎉 MVP 🌈

### ISSUE THREAD

**Issue by ayuspark** [Myao-mirror/mirror-webapp#6]
- [x] web app with components
- [x] component can be draggable
- [x] maybe deploy the webapp so that we can use different device to mount behind the mirror*
- [x] store-managed states
- [x] voice kit integration
   + send json data to webapp
   + or use other means to communicate to the webapp
   + component can be shown using voice control

**Comment by makijurowski** [comment]
Met all of our Epic goals on time back in December 2017! Great job leading this one, @ayuspark.
